@baseUrl = http://localhost:4001

### Get all Authors
GET {{baseUrl}}/authors

###

### Get a specific book by ID
GET {{baseUrl}}/authors/682a2658410355108c7efd72

###

### Get a specific book by ID
POST  {{baseUrl}}/authors

###