@baseUrl = http://localhost:4001

### Get all books
GET {{baseUrl}}/books

###

### Get a specific book by ID
GET {{baseUrl}}/books/682a245519abca3087e0f2ee

###


### Create a new book
POST {{baseUrl}}/books
Content-Type: application/json

  {
    "isbn": "9789645293521",
    "title": "Guidance From the Holy Qur'an",
    "description": "Thematic explanation of key Qur'anic concepts from a Shi’a perspective.",
    "unitPrice": 11.00,
    "stock": 40,
    "image": "https://www.al-islam.org/sites/default/files/images/guidance_from_holy_quran.jpg",
    "category": "Qur'anic Studies",
    "publisher": "Ansariyan Publications",
    "publicationDate": "2002-01-01",
    "pages": 220,
    "language": "English",
    "authorName": "Ayatollah Dastghaib Shirazi",
    "authorBiography": "A prominent Iranian Ayatollah known for accessible Islamic education and ethics."
  }