@baseUrl = http://localhost:4001


###


### Create a new book
POST {{baseUrl}}/sign-up
Content-Type: application/json

  {
        "first": "Sayed Ahmed",
        "last": "Kadhem",
        "email": "s.ahmad@gmail.com",
        "password": "11223344",
        "confirmPassword": "11223344",
        "address": "Manama-Bahrain",
        "phone": "33040006",
        "role":"Admin"
  }


###